### PR TITLE
Convert over to web-component-tester (compat mode)

### PR DESCRIPTION
**Pull request by nevir**
@sorvell @sjmiles @azakus

### CODE REVIEW

**Comment by nevir** [comment]
Note the failure there - there are a few flaky tests:
- [property-array-changes](https://github.com/Polymer/polymer-dev/blob/wct/test/html/property-array-changes.html#L101)
- [mdv-shadow](https://github.com/Polymer/polymer-dev/blob/wct/test/html/mdv-shadow.html), but I'm unclear on which tests are flaking out yet

**Comment by nevir** [comment]
@sorvell I think we should merge this regardless of flakes, get people used to the new flow - assuming you like the organization

**Comment by nevir** [comment]
Also note that the `html/url.html` test is expected until @azakus has a fix in for hash URLs (we shouldn't rewrite `#foo` to include the containing document's search)

(The new test runner tacks search values onto sub suites, is why it's showing up here and not via the old method)

**Comment by dfreedm** [comment]
should be fixed already (#110)

**Comment by nevir** [comment]
Rebased w/ it. Here we go!

**Comment by sorvell** [comment]
LGTM

**Pull request merged**
