### PR TITLE
Remove unneeded array check arg transform

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by sjmiles** [comment]
Constructing throw-away objects (`[]` in this case) is bad for memory management and performance. Sometimes we use `Array.prototype.slice.call`, but never `[].slice`. 

The existing code is a bit verbose, you are not wrong about that, but it was done that way in the interest of code clarity. It may not be the right trade-off, but it's not worth changing at this time.

**Comment by samccone** [comment]
if we used Array.prototype.slice would you be ok with it? 

seems like it is unneeded logic as is? Or is it not worth the technical risk to refactor this with no clear benefit? 

> just trying to help

**Comment by sjmiles** [comment]
`args` may not be an array, in which case it must be encased in one before being sent to `apply`.

IOW, `this.async(foo, 'curried value')` is supported.

**Comment by samccone** [comment]
:+1: :ship: thanks for explaining

**Pull request closed without merging**
